title: Krishna's Website
author: Krishna Duvvuri
email: krishna.c.duvvuri@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My portfolio where I showcase my projects. I also write about meta changes in our society.
  Topics include: AI, blockchain development, data analytics, graphs, cooking, and gaming.

show_excerpts: true # set to false to remove excerpts on the homepage
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
google_analytics: UA-199338542-2
github:
  is_project_page: false
