title: Krishnas Blog
author: Krishna Duvvuri
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog where I talk about things I am learning about. 
  Topics include: AI, Data Science, Graph Databases, Cooking, and Rocket League.

# social links
twitter_username: duvvuri_krishna # DO NOT include the @ character, or else the build will fail!
github_username:  KrishnaCD93 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
