title: Krishna's Website
author: Krishna Duvvuri
email: krishna.c.duvvuri@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My portfolio where I showcase the things I am learning about and building. 
  Topics include: AI, blockchain development, data analytics, graphs, cooking, and gaming.

# social links
twitter_username: duvvuri_krishna # DO NOT include the @ character, or else the build will fail!
github_username:  KrishnaCD93 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
